"""
This script creates the index.html for all the projects (and orgs).

e.g.
/metrics/twitter
/metrics/twitter/twemoji
"""

from glob import glob
import os

PATH_TO_METRICS_POSTS = "_posts"
PATH_TO_GRAPHS = "graphs"

ALL_ORGS = filter(os.path.isdir, glob(PATH_TO_METRICS_POSTS + "/*"))
ALL_PROJECTS = filter(os.path.isdir, glob(PATH_TO_METRICS_POSTS + "/*/*"))

project_text = """\
---
layout: default
permalink: /{org}/{repo}/
---
Welcome to {repo}'s metrics homepage!
<br><br>
Latest WEEKLY Report - <a href="{weekly_metrics_link}">{weekly_metrics_link}</a>
<br>
Latest MONTHLY Report - <a href="{monthly_metrics_link}">{monthly_metrics_link}</a>
<br>
"""

for project in ALL_PROJECTS:
    print("LOG: Starting with", project)
    _, org, repo = project.split("/")
    weekly_metrics_link = "https://twitter.github.io/metrics/{}/{}/WEEKLY".format(org, repo)
    monthly_metrics_link = "https://twitter.github.io/metrics/{}/{}/MONTHLY".format(org, repo)
    _text = project_text.format(org=org,
                                repo=repo,
                                weekly_metrics_link=weekly_metrics_link,
                                monthly_metrics_link=monthly_metrics_link)
    file_path = project + "/" + "2018-05-29-index.md"  # Don't change the date. This prevents duplicate posts.
    with open(file_path, "w+") as f:
        f.write(_text)
    print("LOG: Wrote to", file_path)

org_text = """\
---
layout: org-homepage
permalink: /{org}/
---
<div class="content-without-graphs">
    Welcome to {org}'s metrics homepage!
    <br><br>
    Latest WEEKLY Report - <a href="{weekly_metrics_link}">{weekly_metrics_link}</a>
    <br>
    Latest MONTHLY Report - <a href="{monthly_metrics_link}">{monthly_metrics_link}</a>
    <br>
</div>
"""

for _org in ALL_ORGS:
    print("LOG: Starting with", _org)
    _, org = _org.split("/")
    weekly_metrics_link = "https://twitter.github.io/metrics/{}/WEEKLY".format(org)
    monthly_metrics_link = "https://twitter.github.io/metrics/{}/MONTHLY".format(org)
    file_text = org_text.format(org=org,
                                weekly_metrics_link=weekly_metrics_link,
                                monthly_metrics_link=monthly_metrics_link)

    """
    Add svg graphs generated by scripts/gen_graphs.py
    """
    # timeseries graphs
    all_timeseries_graphs = glob(PATH_TO_GRAPHS + "/" + org + "/timeseries_*.svg")
    file_text += '<p><b>Timeseries graphs</b></p>\n'
    file_text += '<div class="row">\n'
    for graph in all_timeseries_graphs:
        file_text += '\t<object class="cell" type="image/svg+xml" data="{{{{ site.url }}}}{{{{ site.baseurl }}}}/{}">\n'.format(graph)
        file_text += '\t\tYour browser does not support SVG\n'
        file_text += '\t</object>\n'
    file_text += '</div>\n'

    # # Treemap graphs
    # all_treemap_graphs = glob(PATH_TO_GRAPHS + "/" + org + "/treemap_*.svg")
    # file_text += '<p><b>Binary Treemap graphs</b> (recent week)</p>\n'
    # file_text += '<div class="row">\n'
    # for graph in all_treemap_graphs:
    #     file_text += '\t<object class="cell" type="image/svg+xml" data="{{{{ site.url }}}}{{{{ site.baseurl }}}}/{}">\n'.format(graph)
    #     file_text += '\t\tYour browser does not support SVG\n'
    #     file_text += '\t</object>\n'
    # file_text += '</div>\n'


    file_path = _org + "/" + "2018-05-29-index.md"  # Don't change the date. This prevents duplicate posts.
    with open(file_path, "w+") as f:
        f.write(file_text)
    print("LOG: Wrote to", file_path)
